name: CI/CD Pipeline - Deploy

on:
  workflow_run:
    workflows: ["CI/CD Pipeline - Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into server and clone or pull repo
        run: |
          ssh -o StrictHostKeyChecking=no root@64.225.62.232 << 'EOF'
            cd apps/ibis-poc-frontend

            if [ -d ".git" ]; then
              git pull origin master
            else
              git clone https://github.com/ibis-miguel/ibis-poc-frontend.git .
            fi
          EOF
