name: CI/CD Pipeline (Build and Deploy to Server)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install

    - name: Build Angular project
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into server and deploy
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@64.225.62.232 << 'EOF'
     
          cd /apps/ibis-poc-frontend || exit

          git pull origin master

          # docker ps -q --filter "name=my-angular-app" | xargs docker stop | xargs docker rm || true

          docker build -t my-angular-app:latest .

          docker-compose down || true

          docker run -d -p 80:80 my-angular-app:latest

        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

